[package]
name = "its-classified-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "its-classified"
path = "src/main.rs"
doc = false

[dependencies]
its-classified = { path = ".." }
clap = { version = "4", features = ["derive"] }
zeroize = "1"
rand = { version = "0.8", features = ["std", "std_rng"] }

[dev-dependencies]
tempfile = "3"
serde_json = "1"
toml = "0.8"

[features]
test-e2e = []
